[keys]
# CircleCI 
circleci_org_slug = "YOUR_CIRCLECI_ORG_SLUG" # Akin to github/your_user_name
circleci_org_id = "YOUR_CIRCLECI_ORG_ID" # The ID of your org - get it in org settings
circleci_token = "YOUR_CIRCLECI_TOKEN" # Generate in CircleCI account settings

# Third party
snyk_token = "YOUR_SNYK_TOKEN"
docker_login = "YOUR_DOCKER_USERNAME"
docker_token = "YOUR_DOCKER_TOKEN"
digital_ocean_token = "YOUR_DIGITAL_OCEAN_TOKEN"
tf_cloud_org_email = "YOUR_TERRAFORM_ACCOUNT_EMAIL_ADDRESS"

# Do not alter these values for the purposes of this workshop
tf_cloud_org_name = "circleci-demo"
tf_cloud_workspace = "circleci-workshop"
